version: "3.7"
services:
    rabbitmq:
        hostname: rabbitmq
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=guest_user
            - RABBITMQ_DEFAULT_PASS=guest_pass
        ports:
            - "5672:5672"
    worker:
        hostname: worker
        build:
          context: .
          dockerfile: "./Dockerfile.worker"
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - REDIS_CELERY_DB_INDEX=10
            - REDIS_STORE_DB_INDEX=0
            - RABBITMQ_HOST=rabbitmq
            - RABBITMQ_USERNAME=guest
            - RABBITMQ_PASSWORD=guest
            - RABBITMQ_PORT=5672
        depends_on:
            - rabbitmq
            - redis
    redis:
        hostname: redis
        image: redis:latest
        ports:
            - "6379:6379"
    api:
        hostname: api
        build:
          context: .
          dockerfile: './Dockerfile.api'
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - REDIS_CELERY_DB_INDEX=10
            - REDIS_STORE_DB_INDEX=0
            - RABBITMQ_HOST=rabbitmq
            - RABBITMQ_USERNAME=guest
            - RABBITMQ_PASSWORD=guest
            - RABBITMQ_PORT=5672
        volumes:
            - ./src:/usr/src/
        depends_on:
            - worker
        ports:
            - "5000:5000"
    flower:
        build: 
          context: .
          dockerfile: './Dockerfile.flower'
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - REDIS_CELERY_DB_INDEX=10
            - REDIS_STORE_DB_INDEX=0
            - RABBITMQ_HOST=rabbitmq
            - RABBITMQ_USERNAME=guest
            - RABBITMQ_PASSWORD=guest
            - RABBITMQ_PORT=5672
        ports:
            - 5555:5555
        depends_on:
            - rabbitmq
            - redis