  
FROM python:3.9

COPY ./src ./usr/src

COPY ./requirements.txt ./usr/

WORKDIR /usr

RUN pip install -r requirements.txt
EXPOSE 5000

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "5000"]